(******************************************************************************)
(*                                                                            *)
(*            Bounded Enforcement in Deontic Obligation Systems               *)
(*                                                                            *)
(*     Deontic logic framework with obligations, violations, and bounded      *)
(*     enforcement rights. Proves that no consistent assignment of            *)
(*     enforcement authority can authorize unbounded punitive response        *)
(*     to a single obligation violation.                                      *)
(*                                                                            *)
(*     "There is no crueler tyranny than that which is perpetuated            *)
(*     under the shield of law and in the name of justice."                   *)
(*     – Montesquieu, 1748                                                    *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: February 10, 2026                                                *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
