(******************************************************************************)
(*                                                                            *)
(*            Bounded Enforcement in Deontic Obligation Systems               *)
(*                                                                            *)
(*     Deontic logic framework with obligations, violations, and bounded      *)
(*     enforcement rights. Proves that no consistent assignment of            *)
(*     enforcement authority can authorize unbounded punitive response        *)
(*     to a single obligation violation. The Homeworld (1999) universe        *)
(*     supplies the concrete examples that instantiate every schema.          *)
(*                                                                            *)
(*     "The captain claimed our planet violated a 4000 year old treaty        *)
(*     forbidding us to develop hyperspace technology. Extermination          *)
(*     of our planet was the consequence."                                    *)
(*     – Fleet Intelligence                                                   *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: February 10, 2026                                                *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
